# Generated by Django 4.0.2 on 2022-02-16 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_categorie_post_image_alter_post_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
