# Generated by Django 4.0.2 on 2022-02-18 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_blogcomments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomments',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='blogcomments',
            old_name='comments',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='blogcomments',
            old_name='timestamp',
            new_name='date_posted',
        ),
        migrations.RemoveField(
            model_name='blogcomments',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='blogcomments',
            name='post',
        ),
        migrations.RemoveField(
            model_name='blogcomments',
            name='sno',
        ),
        migrations.AddField(
            model_name='blogcomments',
            name='blogpost_connected',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='web.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogcomments',
            name='id',
            field=models.BigAutoField(auto_created=True, default='1', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
