# Generated by Django 4.0.2 on 2022-02-18 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_rename_user_blogcomments_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomments',
            old_name='content',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='blogcomments',
            old_name='blogpost_connected',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='blogcomments',
            old_name='author',
            new_name='user',
        ),
    ]
