# Generated by Django 4.0.2 on 2022-02-20 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_rename_content_blogcomments_comment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogcomments',
        ),
    ]
