# Generated by Django 3.2.12 on 2022-02-27 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20220227_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='cat_slug',
        ),
    ]
