# Generated by Django 3.2.12 on 2022-02-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_remove_categorie_cat_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='cat_slug',
            field=models.SlugField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
