# Generated by Django 3.2.12 on 2022-02-27 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20220227_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='reply',
            new_name='parent',
        ),
    ]
