# Generated by Django 3.2.12 on 2022-02-27 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_rename_reply_comments_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
