# Generated by Django 3.2.12 on 2022-02-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='image', upload_to='featured_image/%Y/%m/%d/'),
        ),
    ]
