# Generated by Django 3.2.12 on 2022-02-28 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='pslug',
            new_name='slug',
        ),
    ]
