# Generated by Django 3.2.12 on 2022-03-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_rename_pslug_page_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='/media/featured_image/2022/02/28/fi.jpg', upload_to='featured_image/%Y/%m/%d/'),
        ),
    ]
